language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131
notifications:
    email: false
install:
    - dotnet restore
script:
    - dotnet build */**/project.json
    - dotnet test test/VstsNotifications.Services.Tests/project.json
    - dotnet test test/VstsNotifications.Webhooks.Tests/project.json